CREATE TABLE IF NOT EXISTS Users(
      ID INT NOT NULL UNIQUE AUTO_INCREMENT,
      Title VARCHAR(255) NOT NULL,
      AuthorID INT,
      FOREIGN KEY (AuthorID) REFERENCES Authors(ID),
      PRIMARY KEY (ID)
)